name: Build image and Push
on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t leteatgoapi ./api/

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to DockerHub
        run: |
          docker tag leteatgoapi ${{ secrets.DOCKER_USERNAME }}/leteatgoapi:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/leteatgoapi:latest
